# Generated by Django 3.1.5 on 2021-01-16 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('aliases', models.CharField(max_length=70)),
                ('amount', models.FloatField()),
                ('expiration', models.DateField()),
            ],
        ),
    ]
