# Generated by Django 3.1.5 on 2021-01-16 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='aliases',
            field=models.CharField(blank=True, max_length=70),
        ),
    ]
